version: '3.8'

services:
  usersDatabase:
    container_name: usersDatabase
    image: mysql:8.0.36
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  booksDatabase:
    container_name: booksDatabase
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=book
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true


  user-service:
    container_name: users_service
    image: springboot-app
    build: ./users-service
    ports:
      - "8085:8085"
    depends_on:
      - usersDatabase
    networks:
      - spring-network

  books-service:
    container_name: books_service
    image: springboot-app
    build: ./book-service
    ports:
      - "8086:8086"
    depends_on:
      - booksDatabase
    networks:
      - spring-network


networks:
  spring-network: