version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - book-service
      - user-service
      - borrow-service
      - payment-service
      - sp-service
      - recommendation-service

  book-service:
    build: ./book-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://books-db:3306/books-db
    depends_on:
      - books-db

  user-service:
    build: ./user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://users-db:3306/users-db
    depends_on:
      - users-db

  borrow-service:
    build: ./borrow-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://books-db:3306/books-db
    depends_on:
      - books-db

  payment-service:
    build: ./payment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://payment-db:3306/payment-db
    depends_on:
      - payment-db

  sp-service:
    build: ./subscription-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sp-db:3306/sp-db
    depends_on:
      - sp-db

  recommendation-service:
    build: ./recommendation-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://books-db:3306/books-db
    depends_on:
      - books-db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  books-db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=books-db
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - books-data:/var/lib/mysql

  users-db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=users-db
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - users-data:/var/lib/mysql

  payment-db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=payment-db
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - payment-data:/var/lib/mysql

  sp-db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=sp-db
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - sp-data:/var/lib/mysql

volumes:
  books-data:
  users-data:
  payment-data:
  sp-data:
