server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://booksdb:3308/book?allowPublicKeyRetrieval=true
    username: library
    password: library
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
