server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/users/**


        - id: books
          uri: http://localhost:8082
          predicates:
            - Path=/books/**


        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/payment/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true