server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api

        - id: books
          uri: http://localhost:8082
          predicates:
            - Path=/books/**
          filters:
            - PrefixPath=/api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true