server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: borrow
          uri: http://localhost:8084
          predicates:
            - Path=/api/borrow/**

        - id: books
          uri: http://localhost:8082
          predicates:
            - Path=/api/books/**

        - id: payment
          uri: http://localhost:8085
          predicates:
            - Path=/api/payment/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true